# Generated by Django 4.2.7 on 2025-10-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_userprofile_privy_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wallet_address',
            field=models.CharField(blank=True, db_index=True, max_length=42, null=True, unique=True),
        ),
    ]
