# Generated by Django 4.2.7 on 2025-10-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_alter_userprofile_telegram_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='seller_contact',
            field=models.CharField(blank=True, help_text='Contact info for direct payment method (email, telegram, etc)', max_length=200, null=True),
        ),
    ]
