# Generated by Django 4.2.7 on 2025-10-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_listing_seller_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='escrow_type',
            field=models.CharField(blank=True, choices=[('disputable', 'Disputable'), ('api_approval', 'API Approval'), ('onchain_approval', 'On-chain Approval')], help_text='Type of escrow (only for escrow payment method)', max_length=20, null=True),
        ),
    ]
