# Generated by Django 4.2.7 on 2025-10-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0018_listing_escrow_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='blockchain_expiration',
            field=models.BigIntegerField(blank=True, help_text='Unix timestamp for blockchain expiration', null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='blockchain_listing_id',
            field=models.CharField(blank=True, help_text='bytes32 listing ID on blockchain (0x...)', max_length=66, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='blockchain_status',
            field=models.CharField(blank=True, help_text='pending_tx, confirmed, failed', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='creation_tx_hash',
            field=models.CharField(blank=True, help_text='Transaction hash for createListing', max_length=66, null=True),
        ),
    ]
