# Generated by Django 4.2.7 on 2025-10-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0019_listing_blockchain_expiration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('filled', 'Filled'), ('delivered', 'Delivered'), ('released', 'Released'), ('refunded', 'Refunded'), ('disputed', 'Disputed'), ('canceled', 'Canceled'), ('inactive', 'Inactive')], default='open', max_length=20),
        ),
    ]
