# Generated by Django 4.2.7 on 2025-10-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0020_alter_listing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='token_decimals',
            field=models.IntegerField(default=6, help_text='Token decimals (e.g., 6 for USDC/USDT)'),
        ),
    ]
