# Generated by Django 4.2.7 on 2025-10-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0021_listing_token_decimals'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='When seller marked as delivered', null=True),
        ),
    ]
