# Generated by Django 4.2.7 on 2025-10-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0021_listing_token_decimals'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='api_approval_method',
            field=models.CharField(blank=True, help_text='API approval method: tweet_repost, crosschain_nft', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='crosschain_nft_contract',
            field=models.CharField(blank=True, help_text='NFT contract address for crosschain verification', max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='crosschain_rpc_url',
            field=models.CharField(blank=True, help_text='RPC URL for crosschain NFT verification', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='crosschain_token_id',
            field=models.CharField(blank=True, help_text='Token ID for crosschain NFT verification', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='tweet_username',
            field=models.CharField(blank=True, help_text='Twitter username for repost verification', max_length=100, null=True),
        ),
    ]
