# Generated by Django 4.2.7 on 2025-10-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0022_listing_api_approval_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='currency',
            field=models.CharField(choices=[('PYUSD', 'PayPal USD')], default='PYUSD', max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='token_decimals',
            field=models.IntegerField(default=6, help_text='Token decimals (e.g., 6 for PYUSD)'),
        ),
    ]
    
