# Generated by Django 4.2.7 on 2025-10-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0023_order_delivered_at_alter_listing_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tweet_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
